### ISSUE TITLE
Default auto-fills on k

### ISSUE THREAD

**Issue by mhkeller** [mhkeller/inquirer-input-up#4]
Keypress on the letter <kbd>k</kbd> is equivalent to hitting up arrow. [edit] this is probably some normalization where <kbd>j</kbd> and <kbd>k</kbd> map to down and up

**Comment by brittharr** [comment]
this is [by design](https://github.com/SBoudrias/Inquirer.js/blob/master/lib/utils/events.js#L20) since "k" is up in vi. not sure how to account for not overwriting everytime you press "k" though...

**Comment by mhkeller** [comment]
should prolly switch it to `e.key.name === 'up'` and not use the normalized value

**Comment by mhkeller** [comment]
Closed closed closed https://github.com/mhkeller/inquirer-input-up/commit/ce30e9a271908a1d60125ab9f2304909204c0eb6
